<?php

namespace QCM\webserviceBundle\Repository;

/**
 * Group_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group_userRepository extends \Doctrine\ORM\EntityRepository
{
}
