<?php

namespace QCM\webserviceBundle\Repository;

/**
 * GroupUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupUserRepository extends \Doctrine\ORM\EntityRepository
{
}
