#src/QCM/webserviceBundle/Resources/config/routing_rest.yml
users : 
    type: rest
    resource:     QCM\webserviceBundle\Controller\UserRestController
    name_prefix:  api_

update_qcm:
    pattern: /update_qcm
    defaults: { _controller:QCMwebserviceBundle:QcmRest:updateQcm}

post_connection:
    pattern: /auth
    defaults: { _controller:QCMwebserviceBundle:AuthRest:postConnection}