services:

####################################################     Groupe Questionnaire    ####################################################
    admin.qcm:
        class: Admin\AdminBundle\Admin\QcmAdmin
        arguments: [~, QCM\webserviceBundle\Entity\Qcm, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Questionnaires, label: Qcm }

    admin.category:
        class: Admin\AdminBundle\Admin\CategoryAdmin
        arguments: [~, QCM\webserviceBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Questionnaires, label: Catégorie }

    admin.question:
        class: Admin\AdminBundle\Admin\QuestionAdmin
        arguments: [~, QCM\webserviceBundle\Entity\Question, AdminAdminBundleAdmin:QuestionAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Questionnaires, label: Question, label_catalogue: SonataAdminBundle, label_translator_strategy: sonata.admin.label.strategy.underscore}

    admin.answer:
        class: Admin\AdminBundle\Admin\AnswerAdmin
        arguments: [~, QCM\webserviceBundle\Entity\Answer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Questionnaires, label: Réponse }

    admin.media:
        class: Admin\AdminBundle\Admin\MediaAdmin
        arguments: [~, QCM\webserviceBundle\Entity\Media, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Questionnaires, label: Média }

    admin.type_media:
        class: Admin\AdminBundle\Admin\TypeMediaAdmin
        arguments: [~, QCM\webserviceBundle\Entity\TypeMedia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Questionnaires, label: Type de média }

####################################################     Groupe Utilisateurs    ####################################################

    admin.user:
        class: Admin\AdminBundle\Admin\UserAdmin
        arguments: [~, QCM\webserviceBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Utilisateurs, label: Utilisateur }

    admin.group_user:
        class: Admin\AdminBundle\Admin\GroupUserAdmin
        arguments: [~, QCM\webserviceBundle\Entity\GroupUser, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des Utilisateurs, label: Groupe }

####################################################     Groupe Résultats    ####################################################

    admin.result:
        class: Admin\AdminBundle\Admin\User_QcmAdmin
        arguments: [~, QCM\webserviceBundle\Entity\User_Qcm, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des liaisons et des Résultats, label: Utilisateur - QCM }